name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate PKGBUILD
        uses: 2m/arch-pkgbuild-builder@v1.18
        with:
          target: pkgbuild
          pkgname: scala-cli

      - name: Validate .SRCINFO
        uses: 2m/arch-pkgbuild-builder@v1.18
        with:
          target: srcinfo
          pkgname: scala-cli

      - name: Test binary
        uses: 2m/arch-pkgbuild-builder@v1.18
        with:
          target: run
          pkgname: scala-cli
          command: |
            scala-cli --help
            echo -e 'object Hello {\n  def main(args: Array[String]): Unit = println("Hello from Scala")\n}' >Hello.scala
            [[ $(scala-cli Hello.scala) == 'Hello from Scala' ]] && exit 0 || exit 1
