name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate PKGBUILD
        uses: 2m/arch-pkgbuild-builder@v1.18
        with:
          target: pkgbuild
          pkgname: scala-cli

      - name: Validate binary
        uses: 2m/arch-pkgbuild-builder@v1.18
        with:
          target: run
          pkgname: scala-cli
          command: scala-cli --help

      - name: Publish AUR package
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: KSXGitHub/github-actions-deploy-aur@v2.2.5
        with:
          pkgname: scala-cli
          pkgbuild: scala-cli/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
